### ISSUE TITLE
'url' input type doesn't populate relevant input fields, button isn't clickable

### ISSUE THREAD

**Issue by coppinger** [tkdallman/shopify-schema-builder#2]
When attempting to add a 'url' input type into either the 'Settings' area or 'Blocks' area, the relevant input fields don't populate and the 'Confirm' button doesn't do anything when clicked.

Here's a short video I recorded to demonstrate the problem, first showing the intended behaviour on the 'text' input type, and then the bug when choosing the 'url' input type.

[https://monosnap.com/file/NzJARDttzdYL92thCuV8G3QRtwq7CC](Link to Monosnap screen recording)

**Comment by coppinger** [comment]
Sorry, I should add this was on Chrome Version 83.0.4103.116 (Official Build) (64-bit) - (latest version), Windows 10.

I tested in incognito to rule out extensions breaking something.

A quick test on Edge showed the same behaviour.

**Comment by tkdallman** [comment]
updated and fixed now!
